name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  if: github.repository == 'MedVisBonn/eyeseg'
  Release:
    uses: MedVisBonn/eyeseg/.github/workflows/_release.yaml@main
    secrets:
      PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
